### ISSUE TITLE
it has trojan.32[Bug]: 

### ISSUE THREAD

**Issue by nujcaca** [YimMenu/YimMenu#1701]
### Describe the bug

takes all your info

### Steps To Reproduce

![image](https://github.com/YimMenu/YimMenu/assets/139480132/473566fd-2ac5-4fe6-920b-753954f6768b)

### Expected Behavior

hack me

### Screenshots and/or Logs

```
<paste your logs here>
```
![image](https://github.com/YimMenu/YimMenu/assets/139480132/a622acd7-ec35-4fa0-978b-8763e98772c5)

### Store

Other (please mention in "Additional context")

### Additional context

exloader

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by nujcaca** [comment]
it didnt hack me

**Comment by nujcaca** [comment]
> Why are you gay?

what?

**Comment by gir489returns** [comment]
You are gay.

**Comment by nujcaca** [comment]
you are gay

**Comment by Yimura** [comment]
Excuse me what?

**Comment by Yimura** [comment]
What an absolutely god awful issue, I'd have at least expected something tangible as proof. Nope absolutely nothing, if there's an issue, show where this issue is, we can't do anything with this issue. Even less with the images you posted.

At the least post an image of Windows Defender removing or detecting the file.

**Comment by Yimura** [comment]
Which file even is it? Is the injector you used or is it YimMenu.dll?

**Comment by KnollenRick** [comment]
I NEVER experienced a Trojan or another mal-/spyware! It’s definitely NOT the YimMenu.dll. I had the same, but I used „Extreme Injector“! THIS program implements Trojans!
