### ISSUE TITLE
[Bug]: Hotkeys while in textfields

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#1948]
### Describe the bug

When i'm currently in a textfield (socialclub message, sending text message via phone, other popups where you need to enter text), keybinds are still working. This is very FRUSTRATING and LIFE CHANGEING when something is bound to key like a-z.

### Steps To Reproduce

Bind e.g. noclip to n.
Send someone a message (like don't send just click send so gui opens)
Type n in gui
NoClip should enable

### Expected Behavior

NoClip should not enable :D

### Logs and/or screenshots

Nah

### Store

Epic Games

### Additional context

I think that the text gui should be easy. With socialclub idk

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by alyxme** [comment]
just rebind it to non leter key but like Fn

**Comment by pierrelasse** [comment]
How stupid you think i am?

**Comment by alyxme** [comment]
Bool `IS_MP_TEXT_CHAT_TYPING` is presented. So TS feature could be implemented within ez check. Rebinding to Fn is just a quickfix guess.

**Comment by pierrelasse** [comment]
Another bug report in the bug report, i CAN bind something to my mouse keys (at the side of the mouse), but they don't register like when i click them nothing happens. Probably an issue with the listener but idk.

**Comment by alyxme** [comment]
> Bool `IS_MP_TEXT_CHAT_TYPING` is presented. So TS feature could be implemented within ez check. Rebinding to Fn is just a quickfix guess.

By rushing this comment I learned from @xiaoxiao921 to look at existed code before putting new one and not to haste with coding to not forget about suffixes or commas. I'm glad for starting dig into the code only because of YimMenu and personaly thanks to @Yimura. Also it aint easy as how it looks in first.
Related to TS the other bools could be used to check if anything on HUD is active for typing: `IS_SOCIAL_CLUB_ACTIVE`, `DOES_TEXT_BLOCK_EXIST` and `NETWORK_​SEND_​TEXT_​MESSAGE`.
