### ISSUE TITLE
[Improvement]: Refill parachute?

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2071]
### Which feature

Self -> Fill Ammo (or other)

### Reason

Because there is currently no way to refill the parachute

**Comment by xiaoxiao921** [comment]
You can make a lua script for this

**Comment by pierrelasse** [comment]
I know that but it would be nice to have it in the menu. Thats why im making this issue.

**Comment by xiaoxiao921** [comment]
The idea is that such simple features can be written entirely in lua instead, and not further bloat the menu feature set, which is already quite large (we've turned down much larger features in the past because most of the time they can be done entirely in lua).
Just know that the main group of maintainers and contributors won't be working on such requests because of this.
