### ISSUE TITLE
[Request]: Chat Translator Feature

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#2148]
### Problem

GTA Online is a global game, not everyone speaks the same language. Such a feature would allow players to bridge a language divide. 

### Solution

An auto translator for chat. 

### Reason

Useful for player communication where language is a barrier. Another reason to bring players together. 

### Additional context

I know it's a big ask, so I understand if no one wants to tackle it.

**Comment by sch-lda** [comment]
I believe that implementing chat translation is not difficult, but it relies on non-free network services, and it cannot guarantee that people worldwide can access the chosen translation service (Google Translate is unavailable in China,Only a few countries' credit cards are eligible to apply for the DeepL API.). Personally, I think that Yimmenu can provide http APIs to Lua so that people in different regions can develop suitable chat translation Lua as needed. However, I'm not sure how to address the security issues that allowing Lua to access the internet might bring. Is it technically feasible to restrict Lua's access to specific domain whitelists?

**Comment by pierrelasse** [comment]
I think too that they should add http stuff.
It would be cool if there would be permission levels for scripts so normal lvl is 0.
And if you set it to 1, as example it could do http stuff.

**Comment by gir489returns** [comment]
> Make if you want. These devs are assholes for no reason just like stand devs. Fucking divas. Reopen whenever you want.

Wahhhhhhhh they don’t want to sift through 50 fucking logs I submit because I can’t wahhhhhhhh. Shut up.

**Comment by pierrelasse** [comment]
@freemantsinq gib ur discord (if you not mind)
