### ISSUE TITLE
[Bug]: Game crash after some time (even in sp)

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2218]
### Describe the bug

I don't know if this is the right place but when i inject. And idk "play" / afk in sp or mp, i crash without doing anything.
This on (https://github.com/YimMenu/YimMenu/pull/2216)[this] build and on the newest.

### Steps To Reproduce

Go sp or mp.
Inject.
Wait ~~~~20 min?

### Expected Behavior

No crash :D

### Logs and/or screenshots

```
[14:11:38.9395948][INFO/main.cpp:65] Yim's Menu Initializing
[14:11:38.9400101][INFO/main.cpp:66] Git Info
	Branch:	
	Hash:	530f635e6ea79e81556506ff2ecaef4218777194
	Date:	Wed Oct 4 02:25:37 2023
[14:11:38.9400296][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[14:11:38.9402832][INFO/main.cpp:69] Thread pool initialized.
[14:11:38.9449663][INFO/main.cpp:72] Settings Loaded.
[14:11:38.9449712][DEBUG/thread_pool.cpp:95] Thread 20876 executing settings.cpp:12
[14:11:38.9456512][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[14:11:38.9456712][INFO/pointers.cpp:1742] Loading pointers instance from cache
[14:11:38.9456733][INFO/pointers.cpp:1751] Pointers cache: Loading 207 fields from the cache
[14:11:38.9456908][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[14:11:38.9459504][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[14:11:38.9459608][INFO/pointers.cpp:1742] Loading pointers instance from cache
[14:11:38.9459632][INFO/pointers.cpp:1751] Pointers cache: Loading 5 fields from the cache
[14:11:38.9460789][INFO/main.cpp:75] Pointers initialized.
[14:11:38.9467119][INFO/main.cpp:78] Byte Patch Manager initialized.
[14:11:39.7632411][INFO/main.cpp:81] Renderer initialized.
[14:11:40.1215879][INFO/main.cpp:85] Fiber pool initialized.
[14:11:40.2319860][INFO/main.cpp:88] Translation Service initialized.
[14:11:40.2716613][INFO/main.cpp:91] Hooking initialized.
[14:11:40.2815970][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[14:11:40.2816220][INFO/gta_data_service.cpp:172] Loading 1029 peds from cache.
[14:11:40.2823622][INFO/gta_data_service.cpp:190] Loading 810 vehicles from cache.
[14:11:40.2829406][INFO/gta_data_service.cpp:207] Loading 117 weapons from cache.
[14:11:40.2829456][INFO/gta_data_service.cpp:208] Loading 378 weapon components from cache.
[14:11:40.2829743][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[14:11:40.2989192][DEBUG/thread_pool.cpp:95] Thread 6168 executing player_database_service.cpp:285
[14:11:40.2997428][INFO/main.cpp:111] Registered service instances...
[14:11:40.2999239][INFO/main.cpp:132] Scripts registered.
[14:11:40.4733474][INFO/main.cpp:135] Hooking enabled.
[14:11:40.4877690][INFO/main.cpp:138] Dynamic native hooker initialized.
[14:11:40.6163496][INFO/main.cpp:141] Lua manager initialized.
[14:11:40.6362988][INFO/backend.cpp:51] Starting script: Self
[14:11:40.6363689][INFO/backend.cpp:76] Starting script: Weapons
[14:11:40.6371971][INFO/backend.cpp:99] Starting script: Vehicles
[14:11:40.6372186][INFO/backend.cpp:115] Starting script: Miscellaneous
[14:11:40.6372313][INFO/backend.cpp:136] Starting script: Remote
[14:11:40.6372403][INFO/backend.cpp:151] Starting script: Ls customs
[14:11:40.6372453][INFO/backend.cpp:163] Starting script: Rainbow paint
[14:11:40.6372482][INFO/backend.cpp:175] Starting script: Disable Control Action
[14:11:40.6372529][INFO/backend.cpp:188] Starting script: World
[14:11:40.6487709][INFO/tunables_service.cpp:36] Loading tunables from cache
[14:31:31.6614907][WARN/log_message_error_box.cpp:37] Error Code: ERR_MEM_EMBEDDEDALLOC_ALLOC
[14:31:31.6628490][FATAL/log_message_error_box.cpp:14] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF62AEC0000 Size: 66857984
ntdll.dll Base Address: 0x7FFB498F0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFB490A0000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFB473D0000 Size: 1255936
apphelp.dll Base Address: 0x7FFB444A0000 Size: 323584
AcLayers.DLL Base Address: 0x7FFA82530000 Size: 175104
msvcrt.dll Base Address: 0x7FFB48FD0000 Size: 477184
USER32.dll Base Address: 0x7FFB47950000 Size: 584704
win32u.dll Base Address: 0x7FFB476D0000 Size: 42496
GDI32.dll Base Address: 0x7FFB49070000 Size: 61952
gdi32full.dll Base Address: 0x7FFB47160000 Size: 686080
msvcp_win.dll Base Address: 0x7FFB47330000 Size: 344064
ucrtbase.dll Base Address: 0x7FFB46FD0000 Size: 735744
SHELL32.dll Base Address: 0x7FFB48230000 Size: 5804544
SHLWAPI.dll Base Address: 0x7FFB49190000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFB48D70000 Size: 423424
sechost.dll Base Address: 0x7FFB48F20000 Size: 412672
RPCRT4.dll Base Address: 0x7FFB48C20000 Size: 923136
sfc.dll Base Address: 0x235259E0000 Size: 0
WINSPOOL.DRV Base Address: 0x7FFB3A010000 Size: 364544
combase.dll Base Address: 0x7FFB47C30000 Size: 2327040
shcore.dll Base Address: 0x7FFB496E0000 Size: 476672
sfc_os.DLL Base Address: 0x7FFB1DA80000 Size: 28672
AcGenral.DLL Base Address: 0x7FFB17E80000 Size: 243200
ole32.dll Base Address: 0x7FFB47F90000 Size: 832000
USERENV.dll Base Address: 0x7FFB46EC0000 Size: 108032
MPR.dll Base Address: 0x7FFB3F6A0000 Size: 71168
SspiCli.dll Base Address: 0x7FFB46E80000 Size: 123904
IMM32.DLL Base Address: 0x7FFB49160000 Size: 122368
PSAPI.DLL Base Address: 0x7FFB48C10000 Size: 2048
WS2_32.dll Base Address: 0x7FFB48E20000 Size: 275456
CRYPT32.dll Base Address: 0x7FFB47730000 Size: 1100288
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFA93BF0000 Size: 96256
WINTRUST.dll Base Address: 0x7FFB47890000 Size: 292864
VERSION.dll Base Address: 0x7FFB3F050000 Size: 10752
DSOUND.dll Base Address: 0x7FFB2E0A0000 Size: 380928
bcrypt.dll Base Address: 0x7FFB47700000 Size: 102912
OLEAUT32.dll Base Address: 0x7FFB48B40000 Size: 608768
bink2w64.dll Base Address: 0x7FFB0F1E0000 Size: 307712
WINMM.dll Base Address: 0x7FFB3BD70000 Size: 81408
MF.dll Base Address: 0x7FFB2DD90000 Size: 340992
WININET.dll Base Address: 0x7FFB1ED10000 Size: 2019840
MFPlat.DLL Base Address: 0x7FFB2DE20000 Size: 1409536
cfgmgr32.dll Base Address: 0x7FFB47900000 Size: 219136
msdmo.dll Base Address: 0x7FFB41530000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFAA63D0000 Size: 918016
PROPSYS.dll Base Address: 0x7FFB42720000 Size: 631296
d3d9.dll Base Address: 0x7FFAF3B10000 Size: 1371648
WTSAPI32.dll Base Address: 0x7FFB40B80000 Size: 37888
D3DCOMPILER_43.dll Base Address: 0x7FFA85AD0000 Size: 2423296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFB19600000 Size: 48128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
powrprof.dll Base Address: 0x7FFB464F0000 Size: 70656
SETUPAPI.dll Base Address: 0x7FFB49270000 Size: 887808
DINPUT8.dll Base Address: 0x7FFB16D90000 Size: 169472
winmmbase.dll Base Address: 0x7FFB377C0000 Size: 95232
IPHLPAPI.DLL Base Address: 0x7FFB463D0000 Size: 166400
d3dx9_43.dll Base Address: 0x7FFA96910000 Size: 2280960
kernel.appcore.dll Base Address: 0x7FFB457D0000 Size: 16384
windows.storage.dll Base Address: 0x7FFB45020000 Size: 5841408
dwmapi.dll Base Address: 0x7FFB44880000 Size: 99328
OPENGL32.dll Base Address: 0x7FFAA9860000 Size: 909312
Wldp.dll Base Address: 0x7FFB46930000 Size: 94720
GLU32.dll Base Address: 0x7FFB08680000 Size: 122880
MFCORE.DLL Base Address: 0x7FFB2D520000 Size: 3959296
ksuser.dll Base Address: 0x7FFB37670000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFB468A0000 Size: 10752
UMPDC.dll Base Address: 0x7FFB463B0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFB470D0000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFB2CD60000 Size: 105472
MSASN1.dll Base Address: 0x7FFB46BA0000 Size: 34816
inputhost.dll Base Address: 0x7FFB3B8B0000 Size: 976384
wintypes.dll Base Address: 0x7FFB42BA0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFB44260000 Size: 606720
CoreUIComponents.dll Base Address: 0x7FFB43F00000 Size: 1804800
ntmarta.dll Base Address: 0x7FFB460F0000 Size: 140288
dbghelp.dll Base Address: 0x7FFB44CC0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFB2ED80000 Size: 136704
d3d12.dll Base Address: 0x7FFB39070000 Size: 92160
CRYPTSP.dll Base Address: 0x7FFB46970000 Size: 46080
rsaenh.dll Base Address: 0x7FFB45FD0000 Size: 142336
uxtheme.dll Base Address: 0x7FFB445B0000 Size: 382976
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFA7A170000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFB480C0000 Size: 240128
Normaliz.dll Base Address: 0x7FFB48FC0000 Size: 512
Secur32.dll Base Address: 0x7FFB2C250000 Size: 11264
WINHTTP.dll Base Address: 0x7FFB3F4C0000 Size: 845312
VCRUNTIME140.dll Base Address: 0x7FFB36660000 Size: 65024
MSVCP140.dll Base Address: 0x7FFB365D0000 Size: 345600
VCRUNTIME140_1.dll Base Address: 0x7FFB375A0000 Size: 15360
clbcatq.dll Base Address: 0x7FFB48180000 Size: 437760
NSI.dll Base Address: 0x7FFB48B30000 Size: 7680
dhcpcsvc6.DLL Base Address: 0x7FFB40CF0000 Size: 23552
dxdiagn.dll Base Address: 0x7FFB0CD40000 Size: 395264
d3d11.dll Base Address: 0x7FFB42D00000 Size: 1853440
dxgi.dll Base Address: 0x7FFB45820000 Size: 614912
DEVOBJ.dll Base Address: 0x7FFB46D60000 Size: 132608
WMICLNT.dll Base Address: 0x7FFB419B0000 Size: 31744
dhcpcsvc.DLL Base Address: 0x7FFB40C70000 Size: 61440
wbemprox.dll Base Address: 0x7FFB3F080000 Size: 27648
wbemcomn.dll Base Address: 0x7FFB3FCA0000 Size: 328704
mswsock.dll Base Address: 0x7FFB46710000 Size: 331776
wbemsvc.dll Base Address: 0x7FFB3D2D0000 Size: 7168
napinsp.dll Base Address: 0x7FFB2C2D0000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFB2C260000 Size: 66048
wshbth.dll Base Address: 0x7FFB41DE0000 Size: 43008
fastprox.dll Base Address: 0x7FFB3D320000 Size: 708608
NLAapi.dll Base Address: 0x7FFB42260000 Size: 68608
amsi.dll Base Address: 0x7FFB3C730000 Size: 62464
DNSAPI.dll Base Address: 0x7FFB46420000 Size: 595456
profapi.dll Base Address: 0x7FFB46F00000 Size: 88064
winrnr.dll Base Address: 0x7FFB2C130000 Size: 32768
MpOav.dll Base Address: 0x7FFAA7D60000 Size: 204800
nvapi64.dll Base Address: 0x7FFB352E0000 Size: 6282752
cryptnet.dll Base Address: 0x7FFB3E940000 Size: 135168
drvstore.dll Base Address: 0x7FFB3E020000 Size: 979456
D3D10_1.DLL Base Address: 0x7FFB17050000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFB3BC30000 Size: 7680
imagehlp.dll Base Address: 0x7FFB48D50000 Size: 45056
nvspcap64.dll Base Address: 0x7FFB01770000 Size: 2055680
MSCTF.dll Base Address: 0x7FFB49790000 Size: 864256
rasadhlp.dll Base Address: 0x7FFB3D2F0000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFB3F1E0000 Size: 288768
textinputframework.dll Base Address: 0x7FFB3B7B0000 Size: 726016
WINSTA.dll Base Address: 0x7FFB45C60000 Size: 190976
nvldumdx.dll Base Address: 0x7FFB3CCD0000 Size: 591360
nvwgf2umx.dll Base Address: 0x7FFB2F400000 Size: 36396032
MessageBus.dll Base Address: 0x7FFB18900000 Size: 5349888
dxcore.dll Base Address: 0x7FFB41590000 Size: 147968
HID.DLL Base Address: 0x7FFB457C0000 Size: 20480
MMDevApi.dll Base Address: 0x7FFB3FD30000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFB0CB80000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFB3FEA0000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFB44780000 Size: 31744
Windows.UI.dll Base Address: 0x7FFB1DB10000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFB402B0000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFB40030000 Size: 1468416
avrt.dll Base Address: 0x7FFB40D10000 Size: 5632
gpapi.dll Base Address: 0x7FFB457F0000 Size: 69120
WINNSI.DLL Base Address: 0x7FFB41570000 Size: 11776
DPAPI.dll Base Address: 0x7FFB46DC0000 Size: 5632
socialclub.dll Base Address: 0x7FFA7D5D0000 Size: 4990464
chrome_elf.dll Base Address: 0x7FFB0CC10000 Size: 676864
libcef.dll Base Address: 0x7FFA26630000 Size: 109744128
COMDLG32.dll Base Address: 0x7FFB47B50000 Size: 684032
OLEACC.dll Base Address: 0x7FFB39FA0000 Size: 260608
UIAutomationCore.DLL Base Address: 0x7FFB0C580000 Size: 2040832
NETAPI32.dll Base Address: 0x7FFB36550000 Size: 47616
COMCTL32.dll Base Address: 0x7FFB39EC0000 Size: 560128
DWrite.dll Base Address: 0x7FFB1A500000 Size: 1601024
USP10.dll Base Address: 0x7FFAF3D20000 Size: 512
dxva2.dll Base Address: 0x7FFB1DF60000 Size: 96256
credui.dll Base Address: 0x7FFB26F60000 Size: 61952
urlmon.dll Base Address: 0x7FFB2CDA0000 Size: 1282560
ncrypt.dll Base Address: 0x7FFB46A80000 Size: 102400
CRYPTUI.dll Base Address: 0x7FFB20110000 Size: 246272
wevtapi.dll Base Address: 0x7FFB41940000 Size: 296960
ESENT.dll Base Address: 0x7FFB37070000 Size: 2585088
iertutil.dll Base Address: 0x7FFB2CAA0000 Size: 550400
srvcli.dll Base Address: 0x7FFB3F5F0000 Size: 58368
netutils.dll Base Address: 0x7FFB46410000 Size: 19456
WKSCLI.DLL Base Address: 0x7FFB46130000 Size: 51200
SAMCLI.DLL Base Address: 0x7FFB3F6C0000 Size: 61440
NTASN1.dll Base Address: 0x7FFB46A40000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFB45B50000 Size: 364544
fwbase.dll Base Address: 0x7FFB45AD0000 Size: 159744
FWPolicyIOMgr.dll Base Address: 0x7FFB37010000 Size: 216064
wdmaud.drv Base Address: 0x7FFAE71F0000 Size: 193024
msacm32.drv Base Address: 0x7FFB3A8E0000 Size: 17920
MSACM32.dll Base Address: 0x7FFB3A8C0000 Size: 74240
midimap.dll Base Address: 0x7FFB08670000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFB03080000 Size: 42496
YimMenu-dev-530f635e6ea79e81556506ff2ecaef4218777194.dll Base Address: 0x7FFA84360000 Size: 6270464
D3DCOMPILER_47.dll Base Address: 0x7FFB42F70000 Size: 3396608
xinput1_4.dll Base Address: 0x7FFB26240000 Size: 30208
schannel.DLL Base Address: 0x7FFB45EE0000 Size: 480768
mskeyprotect.dll Base Address: 0x7FFB28AD0000 Size: 48640
ncryptsslp.dll Base Address: 0x7FFB2A570000 Size: 78848
Dumping registers:
RAX: 0x1
RCX: 0x23525A50000
RDX: 0x23525A50000
RBX: 0x2367AE018B0
RSI: 0x7FF62CDF8B18
RDI: 0xE24398DB48
RSP: 0xE24398DAA0
RBP: 0x10
R8:  0x23525C24A40
R9:  0x1
R10: 0x8000
R11: 0xE24398DA30
R12: 0x0
R13: 0x269EC3
R14: 0xE24398DED8
R15: 0xE24398DED8
Dumping stacktrace:
[0]	YimMenu-dev-530f635e6ea79e81556506ff2ecaef4218777194.dll+0xE4D74 0x7FFA84444D74
[1]	YimMenu-dev-530f635e6ea79e81556506ff2ecaef4218777194.dll+0xE4D44 0x7FFA84444D44
[2]	GTA5.exe+0x1313BB3 0x7FF62C1D3BB3
[3]	GTA5.exe+0x12F474F 0x7FF62C1B474F
[4]	GTA5.exe+0xA9519E 0x7FF62B95519E
[5]	GTA5.exe+0xA9A279 0x7FF62B95A279
[6]	GTA5.exe+0xAA2B67 0x7FF62B962B67
[7]	GTA5.exe+0x161DEF9 0x7FF62C4DDEF9
[8]	GTA5.exe+0x161D72B 0x7FF62C4DD72B
[9]	GTA5.exe+0x277FA 0x7FF62AEE77FA
[10]	GTA5.exe+0x20F07 0x7FF62AEE0F07
[11]	GTA5.exe+0x161D334 0x7FF62C4DD334
[12]	GTA5.exe+0x1494 0x7FF62AEC1494
[13]	GTA5.exe+0x12F50BB 0x7FF62C1B50BB
[14]	GTA5.exe+0x180FFB0 0x7FF62C6CFFB0
[15]	KERNEL32.DLL BaseThreadInitThunk
[16]	ntdll.dll RtlUserThreadStart
--------End of exception--------
```

### Store

Other (please mention in "Additional context")

### Additional context

AmogusGaming

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [x] I've tested this without co-loading anything.

**Comment by D-Borkan** [comment]
also it happened to me , so this need more fix

**Comment by gir489returns** [comment]
This is the memory pool exhaustion issue, which #2116 introduced a "fix" for, but the static offsets haven't been updated, so the AC runners are being ignored again, so the behavior from #1545 is restored.

**Comment by D-Borkan** [comment]
> This is the memory pool exhaustion issue, which #2116 introduced a "fix" for, but the static offsets haven't been updated, so the AC runners are being ignored again, so the behavior from #1545 is restored.

thanks for the clarification. We hope it will be resolved soon

**Comment by Rabtos** [comment]
Even after unloading the menu, the game still crashes after ~ 20 mins.  with ERR_MEM_EMBEDDEDALLOC_ALLOC error
![grafik](https://github.com/YimMenu/YimMenu/assets/124796345/fc5f30f4-8ed7-4085-bf38-7de95a35072b)

**Comment by ghost** [comment]
yep
just wait for an update

**Comment by szarpii** [comment]
Dear Mr Yimura, and the whole YimMenu crew, You mentioned there:
https://www.unknowncheats.me/forum/grand-theft-auto-v/604781-ticket-rockstar.html

**Comment by Yimura** [comment]
And? I'm sure they're aware of our existence if they've made detections specifically targeting the menu.

**Comment by szarpii** [comment]
It's positive content, not negative content about menu, it's about goodmodders, doing job what rockstar workers should.. sad fact is that CEO of rockstar probably dont have any idea how bad is the situation, people there taking money and acting they doing the job.. they probably filtering informations reaching that guy.. i dont believe ceo n all directors there dont care about anything but sharkcards and money, really, really, really. CEO probably think everything is fine, and keep throwing money for imaginary problems r* crew is solving when in the essence rockstar support just saying everyone to duck off, but in polite way, everytime you trying to contact from any reason, and the rockstar crew is doing nothing, literally nothing... tell me, someone saw ANYTIME active admin in gta online? because i saw, and they called MODDERS.. WE, THE GOOD MODDERS, people who ssending bad people to unskipable intro, who sending there toxic modders, and godmode yolo killers.. modders should be paid by rockstar... thats it... also, is it possible to change someone status from "tutorial-done" from 1, to 0? Maybe not public release, but is this possible to spread that to goodmodders? also, is it possible to do Modders-vote system? Just let's say mysql based list, with players.. if someone gonna rate some player, its saved to database. Upvotes and downvotes, thumbs up and thumbs down, or even more complicated, flagging as possible toxic, possible badmodder, griefer, etc.. it would might be next to other info "Flagged as: None/modder/toxic/griefer/badmodder/goodmodder/helper/talkative etc?" Also, is it possible to show players flagged as modders and friends on top of the playerlist? lets say friends with higher prioryty, highest positions on menu playerlist, modders below that, and if flagsystem would implemented, then flagged ones, first baddest ones, flagged as yolo godmode lobby killers, then other shi***ucks, then normal casual nonflagged random peoople? Sorry that i am using comment here, but somehow i cant add my own topic, proposition.. i would happily contact You man, but cant find any discord or other form of reaching You than here. 

Also, You should add submenu, like "Credits/Support us", where You would put some names, and link to paypal.me.. simply.. You deserve that, You and people who here with You. I am searching online for "admin-like" modders, i would happily invite them to using your menu, let's say GOODMODE menu by Yimura? With some more options, like sending to tutorial, and maybe global chat, something like shutbox on unknowncheats? we would might even build there something like 'ingame-database' for players, looking kinda like forum, but for players, lol.. it would be quite simple from projecting side, like gui, frontend etc, but i if it's about ingame mechanics, coding in ur programing language, i am total newbie 🤣

**Comment by szarpii** [comment]
It's positive content, not negative content about menu, it's about goodmodders, doing job what rockstar workers should.. sad fact is that CEO of rockstar probably dont have any idea how bad is the situation, people there taking money and acting they doing the job.. they probably filtering informations reaching that guy.. i dont believe ceo n all directors there dont care about anything but sharkcards and money, really, really, really. CEO probably think everything is fine, and keep throwing money for imaginary problems r* crew is solving when in the essence rockstar support just saying everyone to duck off, but in polite way, everytime you trying to contact from any reason, and the rockstar crew is doing nothing, literally nothing... tell me, someone saw ANYTIME active admin in gta online? because i saw, and they called MODDERS.. WE, THE GOOD MODDERS, people who ssending bad people to unskipable intro, who sending there toxic modders, and godmode yolo killers.. modders should be paid by rockstar... thats it... also, is it possible to change someone status from "tutorial-done" from 1, to 0? Maybe not public release, but is this possible to spread that to goodmodders? also, is it possible to do Modders-vote system? Just let's say mysql based list, with players.. if someone gonna rate some player, its saved to database. Upvotes and downvotes, thumbs up and thumbs down, or even more complicated, flagging as possible toxic, possible badmodder, griefer, etc.. it would might be next to other info "Flagged as: None/modder/toxic/griefer/badmodder/goodmodder/helper/talkative etc?" Also, is it possible to show players flagged as modders and friends on top of the playerlist? lets say friends with higher prioryty, highest positions on menu playerlist, modders below that, and if flagsystem would implemented, then flagged ones, first baddest ones, flagged as yolo godmode lobby killers, then other shi***ucks, then normal casual nonflagged random peoople? Sorry that i am using comment here, but somehow i cant add my own topic, proposition.. i would happily contact You man, but as Your profile says, DON'T DM on discord, so.. i just leave mine: nwk172 (no hashtags)

Also, You should add submenu, like "Credits/Support us", where You would put some names, and link to paypal.me.. simply.. You deserve that, You and people who here with You. I am searching online for "admin-like" modders, i would happily invite them to using your menu, let's say GOODMODE menu by Yimura? With some more options, like sending to tutorial, and maybe global chat, something like shutbox on unknowncheats? we would might even build there something like 'ingame-database' for players, looking kinda like forum, but for players, lol.. it would be quite simple from projecting side, like gui, frontend etc, but i if it's about ingame mechanics, coding in ur programing language, i am total newbie 🤣

**Comment by szarpii** [comment]
PS: I would LOVE to see simple gui-window when first opening gui after injecting, where it gonna be simple text with just few words like please dont be trash against others, we delivering you powerfull tool against toxic players, bad modders, and other bad people, please dont use that tool to bully good people, dont harass innocent people, etc etc etc, thank you bla bla, also you can support us here, bla bla paypal.me link etc... I know it wont change 80% of people, but if only 20% will rethink their life.. isn't it worthy? or maybe other question.. if just one person gonna change because of that text, isnt that worthy? and if we about worthines.. if just one, or two people gonna pay you 10euro monthly.. it's still something, you can buy a watermelon and eat it, lol.. i mean if you like watermelons, haha..  🤣 
i think You Guys understand my appointment, as You programmers, so... logically thinking people, right? ^^

**Comment by BugisoftRSG** [comment]
copium
