### ISSUE TITLE
[Request]: Expose is_friend

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2267]
### Solution

Expose friends_service::is_friend for example and add network.is_player_a_friend

### `is_player_a_friend(player_idx)`

- **Parameters:**
  - `player_idx` (integer): Index of the player.

- **Returns:**
  - `boolean`: Returns true if the given player is a friend in socialclub.

**Example Usage:**
```lua
boolean = network.is_player_a_friend(player_idx)
```

### Reason

To check if a player is your friend and for example, if you want to do something to everyone except you friends, this would be perfect.

**Comment by ghost** [comment]
I’d like an is friend thing because just last night yim thought my friend tried to crash me so it kicked them and blocked joins from them. Not the first time it’s mistaken a player for a modder. Would definitely be useful to make friends immune to certain things, like maybe under reaction there could be a checkbox called something like “Ignore Friends”

Oh, and as for the false modder detection, it thought they sent me an invalid object crash and I have my reaction for that set to kick them. It happened when they were going to sleep and I was in their mc. I’m not sure exactly what happened but anyway, I know it was false and the protections have break some things when certain missions are involved but nbd.

**Comment by NjuuOwO** [comment]
It's already in the menu
```
bool g_player_service->get_selected()->is_friend()
```

**Comment by NjuuOwO** [comment]
Can't `player::is_friend()` be used for this?

**Comment by szarpii** [comment]
> I’d like an is friend thing because just last night yim thought my friend tried to crash me so it kicked them and blocked joins from them. Not the first time it’s mistaken a player for a modder. Would definitely be useful to make friends immune to certain things, like maybe under reaction there could be a checkbox called something like “Ignore Friends”
> 
> Oh, and as for the false modder detection, it thought they sent me an invalid object crash and I have my reaction for that set to kick them. It happened when they were going to sleep and I was in their mc. I’m not sure exactly what happened but anyway, I know it was false and the protections have break some things when certain missions are involved but nbd.

As I said, you have too agressive protections. You attacking other modders that's why you have crashes. Turn that off, kid
