### ISSUE TITLE
[Bug]: Crash by player

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2366]
### Describe the bug

I got crashed and i somewhere read that you should report crashes and since there was an error i thought that i'd make this issue.

### Steps To Reproduce

Become a time traveler
Become me
Get crashed by that kid again that wasted money in some menu

### Expected Behavior

No error & crash

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13227012/cout.log)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by who-care123** [comment]
seems like submarinecar control crash. `CVehicleControlDataNode`

**Comment by gir489returns** [comment]
> seems like submarinecar control crash. `CVehicleControlDataNode`

We removed the implicit check for submarinecar because it was affecting https://github.com/YimMenu/YimMenu/issues/2053

@maybegreat48 Can you take a look at this and see how to fix both scenarios? Looking at the code it seems stupid why you would go through all the trouble to check if it's a submarinecar to return true only to return true anyway. Maybe determine the source of the out of bounds error and check for that in the sync node?

**Comment by who-care123** [comment]
> > seems like submarinecar control crash. `CVehicleControlDataNode`
> 
> We removed the implicit check for submarinecar because it was affecting #2053
> 
> @maybegreat48 Can you take a look at this and see how to fix both scenarios? Looking at the code it seems stupid why you would go through all the trouble to check if it's a submarinecar to return true only to return true anyway. Maybe determine the source of the out of bounds error and check for that in the sync node?

I noticed that there is a submarinecar control protection in `can_apply_data`. Does it not work?
If it doesnt work, I think the issue is `object->GetGameObject()`

**Comment by gir489returns** [comment]
> I noticed that there is a submarinecar control protection in `can_apply_data`. Does it not work?
> If it doesnt work, I think the issue is `object->GetGameObject()`

https://github.com/Yimura/GTAV-Classes/blob/259b9898465407a309419cb6e6376b17587b0319/network/netObject.hpp#L44

Not sure, is the offset correct?

**Comment by maybegreat48** [comment]
We can't (well we technically can but that requires us to rewrite some code) catch the submarine car crash if the object hasn't been created yet. A good workaround is to simply block control syncs from the creation node but that was reverted to fix a bug I think

**Comment by gir489returns** [comment]
> We can't (well we technically can but that requires us to rewrite some code) catch the submarine car crash if the object hasn't been created yet. A good workaround is to simply block control syncs from the creation node but that was reverted to fix a bug I think

Yes https://github.com/YimMenu/YimMenu/issues/2053

**Comment by gir489returns** [comment]
@pierrelasse Did this occur during freemode? I've noticed a lot of people do this kinda crap in freemode.

**Comment by who-care123** [comment]
> > I noticed that there is a submarinecar control protection in `can_apply_data`. Does it not work?
> > If it doesnt work, I think the issue is `object->GetGameObject()`
> 
> https://github.com/Yimura/GTAV-Classes/blob/259b9898465407a309419cb6e6376b17587b0319/network/netObject.hpp#L44
> 
> Not sure, is the offset correct?

I think is correct.

**Comment by pierrelasse** [comment]
> @pierrelasse Did this occur during freemode? I've noticed a lot of people do this kinda crap in freemode.

Yes the crash was in freemode playing there while a modder was spawning many objects. Maybe this helps.

Today i randomly crashed also in freemode randomly playing. Idk if a modder was this or if it was random. Should i make a new issue for it?
[cout.log](https://github.com/YimMenu/YimMenu/files/13249938/cout.log)

**Comment by gir489returns** [comment]
I mean, most of the team is checked out from GTA V dev. The only reason maybegreat even looked at this was I asked him to. And the only reason I even asked him to was @TSYiMa was nice enough to look into the source of the crash. Pretty much nobody else besides me, yim, xiao and sch-ida are actively working on the menu at the moment. Yim is on feature enhancement with the proxy, Xiao is doing his own thing with a new configuration system, sch-ida is trying to fix the new translation changes for Chinese users and I really am not doing all that much, maybe a ticket or two that seems interesting here and there gets submitted and I take it. But I digress. You can submit another ticket if you really want to.

As for this ticket, we can kinda cheat and just check if this request is coming during freemode and reject it. As @NjuuOwO reported the issue was during missions. As the original submitter of #2053 I'd like his approval on the fix, as I don't want to fix, then break something again in the name of anti-harassment.
