### ISSUE TITLE
[Bug]: Vehicle Fly does not work in first person.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2984]
### Describe the bug

Due to the camera being semi-locked when in a vehicle, the car basically spins around while vehicle fly is enabled. There should be a check to see if the player is in first-person while vehicle fly is enabled, and either disable it, warn them, both or just silently do nothing.

### Steps To Reproduce

Enable Vehicle Flymode.
Enter first person view.
Enter vehicle.
Bug occurs.

### Expected Behavior

TBD

### Logs

![image](https://github.com/YimMenu/YimMenu/assets/100792176/9c012dda-0f4d-45e2-b535-55ba5b860e1c)

It's better than bad, it's good!

### Screenshots / Video

[![Watch the video](https://img.youtube.com/vi/_vl45YiXdaw/maxresdefault.jpg)](https://youtu.be/_vl45YiXdaw)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by rkwapisz** [comment]
It seems that the gameplay camera rotation returned by GET_GAMEPLAY_CAM_ROT is relative to the vehicle's rotation when in first person. It's similar to how some old flight sims behaved with mouse controls... you'd move your mouse cursor to some point on the screen and your ship would "chase" the cursor. In this case, we are at a disadvantage because we have no cursor that can be used as a reference to manually adjust your vehicle's heading.

I've tried clamping the rate at which the vehicle's heading changes with some success, so it doesn't yeet you around at 5,000,000RPM, but it still feels super floaty and generally unpleasant.

I think we should just disable this feature when in first-person mode.
